/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(Bỏ)'} PersonalizedAssessment` | ` PersonalizedAssessment`; params?: Router.UnknownInputParams; } | { pathname: `/AllergyScreen`; params?: Router.UnknownInputParams; } | { pathname: `/HealthConditionScreen`; params?: Router.UnknownInputParams; } | { pathname: `/HealthFormScreen`; params?: Router.UnknownInputParams; } | { pathname: `/HealthGoalScreen`; params?: Router.UnknownInputParams; } | { pathname: `/HealthProfileViewScreen`; params?: Router.UnknownInputParams; } | { pathname: `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/ProductAnalysisScreen`; params?: Router.UnknownInputParams; } | { pathname: `/ProgressBar`; params?: Router.UnknownInputParams; } | { pathname: `/ScanProductScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../_components/Collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/../_components/HapticTab`; params?: Router.UnknownInputParams; } | { pathname: `/../_components/HelloWave`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `${'/(Bỏ)'} PersonalizedAssessment` | ` PersonalizedAssessment`; params?: Router.UnknownOutputParams; } | { pathname: `/AllergyScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/HealthConditionScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/HealthFormScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/HealthGoalScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/HealthProfileViewScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/ProductAnalysisScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/ProgressBar`; params?: Router.UnknownOutputParams; } | { pathname: `/ScanProductScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../_components/Collapsible`; params?: Router.UnknownOutputParams; } | { pathname: `/../_components/HapticTab`; params?: Router.UnknownOutputParams; } | { pathname: `/../_components/HelloWave`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `${'/(Bỏ)'} PersonalizedAssessment${`?${string}` | `#${string}` | ''}` | ` PersonalizedAssessment${`?${string}` | `#${string}` | ''}` | `/AllergyScreen${`?${string}` | `#${string}` | ''}` | `/HealthConditionScreen${`?${string}` | `#${string}` | ''}` | `/HealthFormScreen${`?${string}` | `#${string}` | ''}` | `/HealthGoalScreen${`?${string}` | `#${string}` | ''}` | `/HealthProfileViewScreen${`?${string}` | `#${string}` | ''}` | `/HomeScreen${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/ProductAnalysisScreen${`?${string}` | `#${string}` | ''}` | `/ProgressBar${`?${string}` | `#${string}` | ''}` | `/ScanProductScreen${`?${string}` | `#${string}` | ''}` | `/../_components/Collapsible${`?${string}` | `#${string}` | ''}` | `/../_components/HapticTab${`?${string}` | `#${string}` | ''}` | `/../_components/HelloWave${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(Bỏ)'} PersonalizedAssessment` | ` PersonalizedAssessment`; params?: Router.UnknownInputParams; } | { pathname: `/AllergyScreen`; params?: Router.UnknownInputParams; } | { pathname: `/HealthConditionScreen`; params?: Router.UnknownInputParams; } | { pathname: `/HealthFormScreen`; params?: Router.UnknownInputParams; } | { pathname: `/HealthGoalScreen`; params?: Router.UnknownInputParams; } | { pathname: `/HealthProfileViewScreen`; params?: Router.UnknownInputParams; } | { pathname: `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/ProductAnalysisScreen`; params?: Router.UnknownInputParams; } | { pathname: `/ProgressBar`; params?: Router.UnknownInputParams; } | { pathname: `/ScanProductScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../_components/Collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/../_components/HapticTab`; params?: Router.UnknownInputParams; } | { pathname: `/../_components/HelloWave`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
